
'--------------------------------------------------------------------------------
'---            AUTO GENERATED BY A SCRIPT TO MAKE STEAM GAME TILE            ---
'--------------------------------------------------------------------------------
'--- base on TileIconifier's shortcut's system

'Custom Shortcut Type = "Other"
'Shortcut Name = "{gameName}"
'Shortcut Path = "{shortcutPath}"

Dim targetPath, targetArguments

targetPath = """{steamPath}"""
targetArguments = "{gameURL}"

Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.CurrentDirectory = "{steamDirtectory}"
WshShell.Run targetPath & " " & targetArguments, 1